import 'ai_provider.dart';

class OllamaProvider implements AIProvider {
  final String baseUrl;
  final String modelName;

  OllamaProvider({this.baseUrl = "http://10.0.2.2:11434", this.modelName = "llama3"});

  @override
  String get name => "Ollama ($modelName)";

  @override
  Future<Map<String, dynamic>> generateBriefingJson({
    required String systemPrompt,
    required String userContext,
  }) async {
    // TODO: Implement HTTP Post to Ollama here
    // For now, simulate a network delay and return dummy data to prove the switch works.

    await Future.delayed(const Duration(seconds: 2));

    print("--- OLLAMA PROVIDER CALLED ---");

    return {
      "briefs": [
        {
          "id": "ollama_1",
          "subsector": "Simulation",
          "title": "Ollama Provider Active",
          "summary": "This briefing was generated by the Ollama Provider (Stub). If you see this, the switching logic is working!",
          "severity": "Low",
          "fact_score": 0,
          "sent_score": 0,
          "divergence_tag": "System Check",
          "divergence_desc": "Provider Switch Successful",
          "metrics": {"commodity": "N/A", "price": "0.00", "trend": "0%"},
          "headlines": ["Local LLM Connected"],
          "chart_data": [1.0, 1.0, 1.0, 1.0],
          "is_fallback": true
        }
      ]
    };
  }
}